---
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_pip: true
  ansible_version: 2.9.9
  ansible_verbose: true
  ansible_cfg_path: test/ansible.cfg
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      <<: *default_driver_config
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: fedora-30
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip
  - name: fedora-31
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip
  - name: ubuntu-16.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-20.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-8
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: install_archive
    provisioner:
      playbook: test/integration/install/install_archive/default_playbook.yml
      ansible_extra_flags: '--skip-tags=config,launch'
    verifier:
      inspec_tests:
        - path: test/integration/install/install_archive
  - name: install_package
    provisioner:
      playbook: test/integration/install/install_package/default_playbook.yml
      ansible_extra_flags: '--skip-tags=config,launch'
    verifier:
      inspec_tests:
        - path: test/integration/install/install_package
  - name: install_plugins
    provisioner:
      playbook: test/integration/install/install_plugins/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/install_plugins
  - name: config_grafana_ini
    provisioner:
      playbook: test/integration/config/grafana_ini/default_playbook.yml
      ansible_extra_flags: '--skip-tags=launch'
    verifier:
      inspec_tests:
        - path: test/integration/config/grafana_ini
  - name: config_dashboards
    provisioner:
      playbook: test/integration/config/dashboards/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/dashboards
  - name: config_datasources
    provisioner:
      playbook: test/integration/config/datasources/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/datasources
  - name: config_notifiers
    provisioner:
      playbook: test/integration/config/notifiers/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/notifiers
  - name: launch
    provisioner:
      playbook: test/integration/launch/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch
  - name: uninstall
    provisioner:
      playbook: test/integration/uninstall/default_playbook.yml
      idempotency_test: false
    verifier:
      inspec_tests:
        - path: test/integration/uninstall
  - name: explore
    provisioner:
      playbook: test/integration/explore/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/explore
