---
- name: Ensure existence of config dir
  become: true
  file:
    path: "{{ config_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory
  tags:
    - config

- name: Ensure existence of logs dir
  become: true
  file:
    path: "{{ _logs_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory
  tags:
    - config
    - logs

- name: Ensure existence of data dir
  become: true
  file:
    path: "{{ _data_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory
  tags:
    - config
    - data

- name: Ensure existence of provisioning dir
  become: true
  file:
    path: "{{ _provisioning_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory
  tags:
    - config
    - provisioning

- name: Ensure existence of plugins dir
  become: true
  file:
    path: "{{ _plugins_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory
  tags:
    - config
    - plugins

- name: Include main configuration tasks
  include_tasks: "common/config/grafana_ini.yml"
  tags:
    - config

- name: Include provisioning configuration tasks
  include_tasks: "common/config/{{ item }}.yml"
  with_items: "{{ provision_configs }}"
  tags:
    - config
    - provisioning
