---
- name: Ensure Grafana system group exists
  become: true
  group:
    name: "{{ grafana_group }}"
    state: present
    system: true
  tags:
    - install

- name: Create Grafana system user
  become: true
  user:
    comment: Grafana service account
    name: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false
  tags:
    - install

- name: Create installation directory
  become: true
  when: install_type == "archive"
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
  tags:
    - install

- name: Download Grafana archive ({{ archive_url }})
  become: true
  when: install_type == "archive"
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ (archive_checksum|length > 0) | ternary(checksum_format+':'+archive_checksum, '') }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0775'
  register: archive_tmp
  tags:
    - install

- name: Extract Grafana archive
  become: true
  when: install_type == "archive"
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
  tags:
    - install
